name: Generate Datas

on:
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: domilsongaspar
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
